version: "3.9"

services:
  issuance-service:
    build: ./issuance-service
    ports:
      - "5002:5000"
    volumes:
      - ./issuance-service:/app
      - ./issuance-service/node_modules:/app/node_modules
    env_file:
      - ./issuance-service/.env
    environment:
      - NODE_ENV=development
      - WORKER_ID=worker-1
    command: npx nodemon src/index.ts

  verification-service:
    build: ./verification-service
    ports:
      - "5005:5001"
    volumes:
      - ./verification-service:/app
      - ./verification-service/node_modules:/app/node_modules
    env_file:
      - ./verification-service/.env
    environment:
      - NODE_ENV=development
    command: npx nodemon src/index.ts